name = "cf-postal-worker"
compatibility_date = "2023-01-01"
send_email = [
    {type = "send_email", name = "SEB"}
]

[vars]
SENDER_ADDRESS = "wangliang@toong.eu.org"
SENDER_NAME = "None"
RECIPIENT_ADDRESS = "pantong1995@126.com"
ALLOWED_ORIGINS = "*"
